spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ohyuforyou_db?useUnicode=true&characterEncoding=utf8
    username: ohyuforyou
    password: k7t4FZmQ
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 1
      auto-commit: false
logging:
  level:
    org.dbflute: DEBUG
    org.docksidestage : DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    